apiVersion: v1
kind: Namespace
metadata:
  name: devops-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-prod
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: devops-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: devops-staging
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: devops-prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
